### ISSUE TITLE
Support wrappedInput

### ISSUE THREAD

**Issue by wienczny** [DanSmith83/laravel5-foundation#2]
Currently you cannot specify an <input> with a custom type-Attribute that is wrapped inside a <label>
Please add support for this.

**Comment by DanSmith83** [comment]
Can you give me an example of what you're trying to do.

**Comment by wienczny** [comment]
In FoundationFiveFormBuilder there is no wrappedInput($name, $labelText, $type= 'text', $value = null, $options = [])
I suppose you could do that using **input** and **wrapWithLabel** already. But a wrappedInput is shorter.

I'm using html5 input fields like <input type="date">.
- color
- date
- datetime
- datetime-local
- email
- month
- number
- range
- search
- tel
- time
- url
- week

**Comment by DanSmith83** [comment]
How about `wrappedInput($type, $name, $labelText, $value = null, $options = [])` to keep it consistent with the Laravel Collective form builder?

**Comment by wienczny** [comment]
Should work, too. I reordered the arguments to allow $type to have a default value. Consistency might be more important than that.

**Comment by wienczny** [comment]
Wrong button ;-)

**Comment by DanSmith83** [comment]
Just pushed v0.3.0 with the wrappedInput method :)
